### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by NMBlitstrade** [PrimaverabssDeveloper/ERP10Integration#7]
Good morning, I was trying to use the PlatformSamples example that you provided and every time i try to login the following error occurs:

Object reference not set to an instance of an object.

Stack Trace:
```
07/02/2020 12:08:30: Building preengine context
07/02/2020 12:08:30: Creating objects
07/02/2020 12:08:31: Setting configuration
07/02/2020 12:08:31: Setting transaccao
07/02/2020 12:08:31: Calling AbrePlataformaEmpresa
07/02/2020 12:08:32: Primavera.Platform.Exceptions.ExpectedException: Object reference not set to an instance of an object.
   at StdPlatBS100.StdPlatBS.AbrePlataformaEmpresa(String strEmpresa, StdBETransaccao objTransaccao, StdBSConfApl objConfApl, EnumTipoPlataforma enuTipoPlataforma)
   at Primavera.PlatformSamples.PriEngine.CreatContext(String Company, String User, String Password, String Instance) in C:\Users\inovazul\Desktop\ERP10Integration-master\Primavera.PlatformSamples\Engine\PriEngine.cs:line 63
07/02/2020 12:08:32: Primavera.Platform.Exceptions.ExpectedException: Object reference not set to an instance of an object.
   at StdPlatBS100.StdPlatBS.AbrePlataformaEmpresa(String strEmpresa, StdBETransaccao objTransaccao, StdBSConfApl objConfApl, EnumTipoPlataforma enuTipoPlataforma)
   at Primavera.PlatformSamples.PriEngine.CreatContext(String Company, String User, String Password, String Instance) in C:\Users\inovazul\Desktop\ERP10Integration-master\Primavera.PlatformSamples\Engine\PriEngine.cs:line 71

```

I'm by all means not a c# developer, and have absolutely no experience in Primavera, but here's what I did do setup the program:

1 - Setup the References
I went to Reference manager > Browse and started adding every .dll that was missing in Solution Explorer > Primavera.PlatformSamples > References from `C:\Program Files (x86)\PRIMAVERA\SG100\Apl`

2 - I had to download .net framework 4.7.1 and set it up in Properties > Target framework

Did I do something wrong ? Did I miss something ?
Also, what does the step `7. Set the output path for your solution.` mean?

**Comment by NunoPeixotoPrimavera** [comment]
Hello,
you have to do two simple things:
1. Add a reference path in the project properties to your ERP installation (C:\Program Files (x86)\Primavera\SG100\Apl)
2. Change the following line:
    `           StdLoggingHandler.FileTrace("Setting configuration");
                EnumTipoPlataforma objTipoPlataforma = EnumTipoPlataforma.tpProfissional;` 
For Professional ou Executive.

At class **PriEngine.cs** in function **CreateContext**

**Comment by NMBlitstrade** [comment]
It worked, thanks for the help.
